version: "3.8"
services:
  # Backend Service (Django)
  backend:
    build:
      context: ./  # This points to the webpage directory where your backend Dockerfile is
      dockerfile: Dockerfile.backend  # Dockerfile for backend in /webpage (specify if named differently)
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb+srv://CyberCTF:VaiiMl2KwTfqTUna@cyberctf.ynzom.mongodb.net/?retryWrites=true&w=majority&appName=CyberCTF
    volumes:
      - ./backend:/app  # Mount the backend code into the container
    ports:
      - "8000:8000"  # Expose Django app on port 8000
    depends_on:
      - mongodb  # Ensure backend waits for MongoDB to be ready
    networks:
      - backend_network

  # Frontend Service (React with Vite)
  frontend:
    build:
      context: ./CTFweb  # Path to frontend directory
      dockerfile: Dockerfile  # Dockerfile for React frontend inside /webpage/CTFweb
    container_name: frontend
    ports:
      - "5173:5173"  # Expose React app on port 5173
    environment:
      - VITE_API_URL=http://13.232.52.188:8000/api/  # Pass backend URL to the frontend
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready
    networks:
      - backend_network

  # MongoDB Service (MongoDB Atlas in this case, no need for local container)
  mongodb:
    image: mongo:latest  # No longer needed if using MongoDB Atlas
    container_name: mongodb
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge  # Enables communication between services on the same network
