version: "3.8"
services:
  # Backend Service (Django)
  backend:
    build:
      context: ./  # This points to the backend directory where Dockerfile.backend exists
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb+srv://CyberCTF:VaiiMl2KwTfqTUna@cyberctf.ynzom.mongodb.net/?retryWrites=true&w=majority&appName=CyberCTF # MongoDB URI for Atlas
    volumes:
      - ./backend:/app  # Mount the backend code into the container
      - ./backend/db.sqlite3:/app/db.sqlite3  # If you're still using SQLite for local development
    ports:
      - "8000:8000"  # Expose Django app on port 8000
    networks:
      - backend_network

  # Frontend Service (React with Vite)
  frontend:
    build:
      context: ./CTFweb  # Path to frontend directory
      dockerfile: Dockerfile  # Dockerfile for React frontend inside /webpage/CTFweb
    container_name: frontend
    ports:
      - "5173:5173"  # Expose React app on port 5173
    environment:
      - VITE_API_URL=http://backend:8000/api/  # Pass backend URL to the frontend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
